export const MOCK_CATEGORIES = [
  {
    id: 'cat-1',
    name: 'Ropa & Moda',
    slug: 'ropa',
    description: 'Prendas urbanas, camperas, remeras y calzado de tendencia',
    icon: 'Shirt',
    color: 'from-[#FCE4E6] to-[#F7C6CB]',
    itemCount: 4
  },
  {
    id: 'cat-2',
    name: 'Perfumes & Fragancias',
    slug: 'perfumes',
    description: 'Fragancias exclusivas, perfumes importados y body splash',
    icon: 'Sparkles',
    color: 'from-[#EFE7F7] to-[#D6C4E7]',
    itemCount: 3
  },
  {
    id: 'cat-3',
    name: 'Juguetes & Juegos',
    slug: 'juguetes',
    description: 'Juguetes para todas las edades, juegos de mesa y diversión',
    icon: 'Gamepad2',
    color: 'from-[#FFF0E0] to-[#FCE0C7]',
    itemCount: 3
  },
  {
    id: 'cat-4',
    name: 'Electrónica & Tech',
    slug: 'electronica',
    description: 'Auriculares, smartwatches, parlantes y accesorios móviles',
    icon: 'Headphones',
    color: 'from-[#E6F3F7] to-[#C9E7F0]',
    itemCount: 3
  },
  {
    id: 'cat-5',
    name: 'Hogar & Accesorios',
    slug: 'hogar',
    description: 'Deco, termos, mochilas y artículos esenciales',
    icon: 'Home',
    color: 'from-[#EAF3EB] to-[#CDE4CF]',
    itemCount: 2
  }
];

export const MOCK_PRODUCTS = [
  {
    id: 'prod-1',
    title: 'Campera Bomber Urbana Oversize Premium',
    slug: 'campera-bomber-urbana-oversize',
    description: 'Campera bomber unisex confeccionada en microfibra impermeable de alta densidad. Posee forro térmico acolchado interno, bolsillos laterales con cierre y puños elastizados. Diseño urbano contemporáneo ideal para combinar con cualquier outfit.',
    price: 48500,
    original_price: 62000,
    category_slug: 'ropa',
    category_name: 'Ropa & Moda',
    image_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
    stock: 15,
    is_featured: true,
    is_active: true,
    badge: 'MÁS VENDIDO',
    rating: 4.9,
    reviewsCount: 38,
    tags: ['ropa', 'campera', 'invierno', 'moda', 'urbano']
  },
  {
    id: 'prod-2',
    title: 'Perfume Noir Extreme Eau de Parfum 100ml',
    slug: 'perfume-noir-extreme-100ml',
    description: 'Fragancia masculina intensa y magnética. Combina notas de salida de cardamomo y mandarina, un corazón de flor de azahar y jazmín, sobre una fondo profundo de ámbar, madera de sándalo y vainilla gourmet. Duración de más de 24 hs.',
    price: 54900,
    original_price: 69000,
    category_slug: 'perfumes',
    category_name: 'Perfumes & Fragancias',
    image_url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80',
    stock: 8,
    is_featured: true,
    is_active: true,
    badge: 'OFERTA TOP',
    rating: 5.0,
    reviewsCount: 52,
    tags: ['perfume', 'fragancia', 'hombre', 'lujo']
  },
  {
    id: 'prod-3',
    title: 'Auto Todoterreno RC 4x4 Alta Velocidad',
    slug: 'auto-todoterreno-rc-4x4',
    description: 'Vehículo a control remoto escala 1:16 con tracción 4x4. Equipado con suspensiones independientes de aluminio, neumáticos de goma todoterreno, faros LED frontales y batería recargable de polímero de litio por USB (hasta 40 min de juego contínuo).',
    price: 32500,
    original_price: 41000,
    category_slug: 'juguetes',
    category_name: 'Juguetes & Juegos',
    image_url: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
    stock: 20,
    is_featured: true,
    is_active: true,
    badge: 'NUEVO',
    rating: 4.8,
    reviewsCount: 29,
    tags: ['juguete', 'control remoto', 'niños', 'diversion']
  },
  {
    id: 'prod-4',
    title: 'Auriculares Bluetooth Pro ANC Cancelación Activa',
    slug: 'auriculares-bluetooth-pro-anc',
    description: 'Auriculares in-ear con cancelación activa de ruido ambiental (ANC de 35dB) y modo transparencia. Drivers de titanio de 12mm con bajos profundos, resistencia al agua IPX5 y estuche de carga inteligente con indicador LED.',
    price: 28900,
    original_price: 38000,
    category_slug: 'electronica',
    category_name: 'Electrónica & Tech',
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    stock: 25,
    is_featured: true,
    is_active: true,
    badge: '25% OFF',
    rating: 4.9,
    reviewsCount: 64,
    tags: ['auriculares', 'tech', 'audio', 'bluetooth']
  },
  {
    id: 'prod-5',
    title: 'Perfume Velvet Rose & Oud Luxe 50ml',
    slug: 'perfume-velvet-rose-oud-50ml',
    description: 'Una fragancia femenina envolvente y misteriosa. Destaca por sus acordes de rosa damascena envuelta en matices de clavo de olor, praliné crujiente y la calidez amaderada del Oud ahumado. Presentado en frasco sobrio de cristal tallado.',
    price: 42000,
    original_price: 52000,
    category_slug: 'perfumes',
    category_name: 'Perfumes & Fragancias',
    image_url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80',
    stock: 12,
    is_featured: true,
    is_active: true,
    badge: 'EXCLUSIVO',
    rating: 4.7,
    reviewsCount: 19,
    tags: ['perfume', 'mujer', 'fragancia', 'lujo']
  },
  {
    id: 'prod-6',
    title: 'Zapatillas Urban Retro Skate Unisex',
    slug: 'zapatillas-urban-retro-skate',
    description: 'Calzado urbano inspirado en la cultura retro skate de los 90. Capellada de cuero vacuno y gamuza sintética, suela vulcanizada de goma antideslizante de alta tracción y plantilla amortiguada Memory Foam.',
    price: 39900,
    original_price: 49000,
    category_slug: 'ropa',
    category_name: 'Ropa & Moda',
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    stock: 18,
    is_featured: true,
    is_active: true,
    badge: 'TENDENCIA',
    rating: 4.9,
    reviewsCount: 45,
    tags: ['zapatillas', 'calzado', 'moda', 'ropa']
  },
  {
    id: 'prod-7',
    title: 'Oso de Peluche Gigante 1 Metro Extra Suave',
    slug: 'oso-de-peluche-gigante-1m',
    description: 'Peluche gigante elaborado con felpa antialérgica de máxima suavidad y relleno de algodón sintético esponjoso. Ojos bordados de seguridad. El regalo perfecto para sorprender en cumpleaños y aniversarios.',
    price: 27500,
    original_price: 35000,
    category_slug: 'juguetes',
    category_name: 'Juguetes & Juegos',
    image_url: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=800&q=80',
    stock: 10,
    is_featured: false,
    is_active: true,
    badge: 'REGALO IDEAL',
    rating: 5.0,
    reviewsCount: 31,
    tags: ['peluche', 'juguete', 'amor', 'regalo']
  },
  {
    id: 'prod-8',
    title: 'Smartwatch AMOLED Deportivo con GPS',
    slug: 'smartwatch-amoled-deportivo-gps',
    description: 'Reloj inteligente con pantalla táctil HD AMOLED de 1.43", cuerpo de aleación de zinc y correa de silicona líquida. Incluye monitoreo continuo de ritmo cardíaco, saturación SpO2, calidad del sueño y más de 100 modos deportivos.',
    price: 36900,
    original_price: 48000,
    category_slug: 'electronica',
    category_name: 'Electrónica & Tech',
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    stock: 14,
    is_featured: true,
    is_active: true,
    badge: 'MEJOR PRECIO',
    rating: 4.8,
    reviewsCount: 88,
    tags: ['reloj', 'smartwatch', 'deporte', 'tech']
  },
  {
    id: 'prod-9',
    title: 'Remera Streetwear Oversize 100% Algodón',
    slug: 'remera-streetwear-oversize-cotton',
    description: 'Remera de corte amplio oversize confeccionada en algodón peinado 24/1 de alta dureza. Cuello de rébol reforzado que no se deforma. Estampa gráfica posterior realizada en serigrafía tacto cero.',
    price: 18500,
    original_price: 24000,
    category_slug: 'ropa',
    category_name: 'Ropa & Moda',
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    stock: 30,
    is_featured: false,
    is_active: true,
    badge: 'OFERTA',
    rating: 4.6,
    reviewsCount: 22,
    tags: ['remera', 'streetwear', 'ropa', 'algodon']
  },
  {
    id: 'prod-10',
    title: 'Juego de Mesa Estrategia y Dominio Mundial',
    slug: 'juego-de-mesa-estrategia-suprema',
    description: 'Juego de mesa táctico completo para 2 a 6 jugadores. Incluye tablero ilustrado rígido de 60x80cm, 300 miniaturas plásticas detalladas, fichas metálicas, dados y manual ilustrado con reglas rápidas y avanzadas.',
    price: 29800,
    original_price: 37000,
    category_slug: 'juguetes',
    category_name: 'Juguetes & Juegos',
    image_url: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
    stock: 7,
    is_featured: false,
    is_active: true,
    badge: 'FAMILIAR',
    rating: 4.9,
    reviewsCount: 15,
    tags: ['juegos', 'mesa', 'amigos', 'juguetes']
  },
  {
    id: 'prod-11',
    title: 'Parlante Bluetooth WaterProof Bass 20W',
    slug: 'parlante-bluetooth-waterproof-20w',
    description: 'Parlante portátil inalámbrico con potencia estéreo de 20W y radiador pasivo doble para graves potentes. Certificación impermeable IPX7 para usar en la pileta o playa. Luces LED RGB sincronizadas con el ritmo de la música.',
    price: 24500,
    original_price: 32000,
    category_slug: 'electronica',
    category_name: 'Electrónica & Tech',
    image_url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80',
    stock: 22,
    is_featured: false,
    is_active: true,
    badge: 'IMPERDIBLE',
    rating: 4.7,
    reviewsCount: 41,
    tags: ['parlante', 'musica', 'bluetooth', 'tech']
  },
  {
    id: 'prod-12',
    title: 'Termo de Acero Inoxidable 1.2 Litros TermoPro',
    slug: 'termo-acero-inoxidable-1-2l',
    description: 'Termo matero de grado alimenticio 18/8 con aislamiento por vacío de doble pared. Conserva el agua caliente o helada por más de 24 horas. Tapón cebador de precisión antigoteo y manija rebatible ergonómica.',
    price: 31000,
    original_price: 39000,
    category_slug: 'hogar',
    category_name: 'Hogar & Accesorios',
    image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    stock: 16,
    is_featured: false,
    is_active: true,
    badge: 'CALIDAD TOP',
    rating: 5.0,
    reviewsCount: 73,
    tags: ['termo', 'mate', 'hogar', 'acero']
  }
];
